In [1]:
import kMeans
import numpy as np

# load data

In [2]:
datMat = np.mat(kMeans.loadDataSet('testSet.txt'))
print(min(datMat[:,0]))
print(max(datMat[:,1]))
rand_cent = kMeans.randCent(datMat, 2)
print(rand_cent)

[[-5.379713]]
[[ 5.1904]]
[[ 3.48486382 -0.85515174]
 [ 3.65807803 -0.36616215]]


In [3]:
eucli_distance = kMeans.distEclud(datMat[0], datMat[1])
print(eucli_distance)
print(datMat[0], datMat[1])

5.18463281668
(matrix([[ 1.658985,  4.285136]]), matrix([[-3.453687,  3.424321]]))


# kmeans

In [4]:
myCentroids, clusterAssing = kMeans.kMeans(datMat, 4)
print('centroids: ', myCentroids)

[[-1.75856263 -4.0114871 ]
 [-1.20823422 -1.6765594 ]
 [ 0.51449014 -2.77043053]
 [-1.45491007  3.50343915]]
[[-3.46206847 -3.23436427]
 [-2.52731343 -1.44651771]
 [ 2.97753205 -2.6512067 ]
 [ 0.0469085   3.05287679]]
[[-3.458902   -3.12120435]
 [-3.04707917 -0.29820883]
 [ 2.8692781  -2.54779119]
 [ 0.23721978  3.13048439]]
[[-3.38237045 -2.9473363 ]
 [-3.438104    2.0608484 ]
 [ 2.8692781  -2.54779119]
 [ 0.47923624  3.13206456]]
[[-3.38237045 -2.9473363 ]
 [-2.768021    2.65028438]
 [ 2.8692781  -2.54779119]
 [ 1.88660209  3.23434291]]
[[-3.38237045 -2.9473363 ]
 [-2.46154315  2.78737555]
 [ 2.80293085 -2.7315146 ]
 [ 2.6265299   3.10868015]]
('centroids: ', matrix([[-3.38237045, -2.9473363 ],
        [-2.46154315,  2.78737555],
        [ 2.80293085, -2.7315146 ],
        [ 2.6265299 ,  3.10868015]]))


# binary kmeans

In [5]:
datMat3 = np.mat(kMeans.loadDataSet('testSet2.txt'))
centList, myNewAssments = kMeans.biKmeans(datMat3, 3)
print(centList)

[[ 1.16264945 -4.03060605]
 [ 2.70283828 -3.08016255]]
[[-1.70174271 -0.30206818]
 [ 1.86138027  3.22269712]]
[[-1.72153338 -0.00938424]
 [ 2.35797261  3.21160974]]
[[-1.73028592  0.20133246]
 [ 2.76275171  3.12704005]]
[[-1.70351595  0.27408125]
 [ 2.93386365  3.12782785]]
sseSplit, and notSplit:  541.297629265 0.0
the bestCentToSplit is:  0
the len of bestClustAss is:  60
[[-4.4580937  -3.30907846]
 [-1.71569832  3.62840347]]
[[-0.45965615 -2.7782156 ]
 [-2.94737575  3.3263781 ]]
sseSplit, and notSplit:  67.2202000798 39.5292986821
[[ 1.43677274  2.34601245]
 [ 2.59907669  1.61317406]]
[[ 2.02712544  3.50141167]
 [ 3.67574036  2.82216836]]
sseSplit, and notSplit:  23.7917507304 501.768330583
the bestCentToSplit is:  0
the len of bestClustAss is:  40
[[-0.45965615 -2.7782156 ]
 [ 2.93386365  3.12782785]
 [-2.94737575  3.3263781 ]]


# Yahoo PlaceFinder API

In [6]:
geoResults = kMeans.geoGrab('1 VA Center', 'Augusta, ME')

http://where.yahooapis.com/geocode?flags=J&location=1+VA+Center+Augusta%2C+ME&appid=aaa0VN6k


IOError: [Errno socket error] [Errno 11001] getaddrinfo failed

In [7]:
geoResults['ResultSet']['Results'][0]['longitude']

NameError: name 'geoResults' is not defined

In [8]:
kMeans.massPlaceFind('portlandClubs.txt')

http://where.yahooapis.com/geocode?flags=J&location=10860+SW+Beaverton-Hillsdale+Hwy+Beaverton%2C+OR&appid=aaa0VN6k


IOError: [Errno socket error] [Errno 11001] getaddrinfo failed

# kmenas cluster plot

In [9]:
kMeans.clusterClubs(5)

IndexError: index 1 is out of bounds for axis 1 with size 0