In [7]:
import numpy as np
import svdRec

# numpy svd sample

In [5]:
U, Sigma, VT = np.linalg.svd([[1,1], [7,7]])
print(U)
print(Sigma)
print(VT)

[[-0.14142136 -0.98994949]
 [-0.98994949  0.14142136]]
[ 10.   0.]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


# load data and svd test

In [8]:
Data = svdRec.loadExData()
U, Sigma, VT = np.linalg.svd(Data)
print(Sigma)

[  9.64365076e+00   5.29150262e+00   7.40623935e-16   4.05103551e-16
   2.21838243e-32]


# reconstruct data from svd

In [9]:
Sig3 = np.mat([[Sigma[0], 0, 0], [0, Sigma[1], 0], [0, 0, Sigma[2]]])
recon_data = U[:, :3]*Sig3*VT[:3,:]
print(recon_data)

[[ -1.18596184e-15   7.16503651e-16   4.69458187e-16   2.00000000e+00
    2.00000000e+00]
 [ -7.69233911e-16   3.14619452e-16   4.54614459e-16   3.00000000e+00
    3.00000000e+00]
 [ -2.02143152e-16   6.40186235e-17   1.38124528e-16   1.00000000e+00
    1.00000000e+00]
 [  1.00000000e+00   1.00000000e+00   1.00000000e+00   5.19259273e-17
    5.19259273e-17]
 [  2.00000000e+00   2.00000000e+00   2.00000000e+00   1.03851855e-16
    1.03851855e-16]
 [  5.00000000e+00   5.00000000e+00   5.00000000e+00   2.07703709e-16
    2.07703709e-16]
 [  1.00000000e+00   1.00000000e+00   1.00000000e+00   5.19259273e-17
    5.19259273e-17]]


# collaborative filtering

In [10]:
myMat = np.mat(svdRec.loadExData())
svdRec.ecludSim(myMat[:,0],myMat[:,4])

0.12973190755680383

In [11]:
svdRec.ecludSim(myMat[:,0],myMat[:,0])

1.0

In [12]:
svdRec.cosSim(myMat[:,0], myMat[:,4])

0.5

In [13]:
svdRec.cosSim(myMat[:,0], myMat[:,0])

1.0

In [14]:
svdRec.pearsSim(myMat[:,0], myMat[:,4])

0.20596538173840329

In [15]:
svdRec.pearsSim(myMat[:,0], myMat[:,0])

1.0

# recommend cooked food

In [16]:
myMat = np.mat(svdRec.loadExData())
myMat[0, 1] = myMat[0, 0] = myMat[1, 0] = myMat[2, 0] = 4
myMat[3,3] = 2
print(myMat)

[[4 4 0 2 2]
 [4 0 0 3 3]
 [4 0 0 1 1]
 [1 1 1 2 0]
 [2 2 2 0 0]
 [5 5 5 0 0]
 [1 1 1 0 0]]


In [17]:
svdRec.recommend(myMat, 2)

the 1 and 0 similarity is: 1.000000
the 1 and 3 similarity is: 0.928746
the 1 and 4 similarity is: 1.000000
the 2 and 0 similarity is: 1.000000
the 2 and 3 similarity is: 1.000000
the 2 and 4 similarity is: 0.000000


[(2, 2.5), (1, 2.0243290220056256)]

In [18]:
svdRec.recommend(myMat, 2, simMeas=svdRec.ecludSim)

the 1 and 0 similarity is: 1.000000
the 1 and 3 similarity is: 0.309017
the 1 and 4 similarity is: 0.333333
the 2 and 0 similarity is: 1.000000
the 2 and 3 similarity is: 0.500000
the 2 and 4 similarity is: 0.000000


[(2, 3.0), (1, 2.8266504712098603)]

In [19]:
svdRec.recommend(myMat, 2, simMeas=svdRec.pearsSim)

the 1 and 0 similarity is: 1.000000
the 1 and 3 similarity is: 1.000000
the 1 and 4 similarity is: 1.000000
the 2 and 0 similarity is: 1.000000
the 2 and 3 similarity is: 1.000000
the 2 and 4 similarity is: 0.000000


[(2, 2.5), (1, 2.0)]

## svd process

In [20]:
from numpy import linalg as la
U, Sigma, VT = la.svd(np.mat(svdRec.loadExData2()))
print(Sigma)

[ 15.77075346  11.40670395  11.03044558   4.84639758   3.09292055
   2.58097379   1.00413543   0.72817072   0.43800353   0.22082113
   0.07367823]


In [22]:
Sig2 = Sigma**2
sum(Sig2)

541.99999999999955

In [23]:
sum(Sig2)*0.9

487.79999999999961

In [24]:
sum(Sig2[:2])

378.8295595113579

In [25]:
sum(Sig2[:3])

500.50028912757926

# svd estimator

In [26]:
svdRec.recommend(myMat, 1,  estMethod=svdRec.svdEst)

the 1 and 0 similarity is: 0.498142
the 1 and 3 similarity is: 0.498131
the 1 and 4 similarity is: 0.509974
the 2 and 0 similarity is: 0.552670
the 2 and 3 similarity is: 0.552976
the 2 and 4 similarity is: 0.217301


[(2, 3.4177569186592387), (1, 3.3307171545585641)]

In [27]:
svdRec.recommend(myMat, 1, estMethod=svdRec.svdEst, simMeas=svdRec.pearsSim)

the 1 and 0 similarity is: 0.626075
the 1 and 3 similarity is: 0.672793
the 1 and 4 similarity is: 0.614375
the 2 and 0 similarity is: 0.429334
the 2 and 3 similarity is: 0.387057
the 2 and 4 similarity is: 0.043539


[(2, 3.4992661245386789), (1, 3.3272324280613659)]

# image compress with svd

In [28]:
svdRec.imgCompress(2)

****original matrix******
0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 
0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 